travis:
  secure:
    BINSTAR_TOKEN: ejlCyGffB9+COObeGI8tS73YzqHcQrWiIeM+IadTeq5vu82VMoLk6nJEhvL9hMQe/MPJzIYZjUy6vwukvZrruQ0pIrymOHppGP/3WTvnj88YX+8Yrydb3SAXmiLIVy7H5fDzZ4bzQQ0yOBaDmjCQZEI5CQOtFsZT8lyS56lFlb+f/QorjvgF/8oXmLCiLrFibGSKbLDCm4POkrrGiNpNYfuE9mmhAEV9xeiLc00dDSRrPbzRT3F0w8VRVLVmofXMMA+KnGxvJ56Kr1z6Le4+2yh1ir9UVo/RqjP9Qr3FiYcZO3waZUqv2ssgIF3w7benBt2Yj/pUNAqDYHOreDvP/2pTMQkHzSkOF2sBxjUnYkOyuMNF/QeoSuSO9w7hDUR8bN+O2E5X18cqGvYO46TggtW+hMCoM9EU0tjiACrxoCKNtC3oD8rFEy6L8qsUdHful3lDoBoV2olexL9EEPcNjl5vncBqzSeWTEOGKHEBIBtEiUfs15QgUumpCpSkJxzYmTnGOknie8trjyjDYe3u79zdLxjbUcSSgarzovdSuxk5PE+woZ862CHaeiX0EgL90HDJYI48YVji9lgp/uLNv8OQsj+YboLv5Z19oFQWZxIXuHQ3uLTyQQhGkMj7u7L4sbk5mbzd4V0x78b7THAB/mwdGMhetveQAwPZ535PqU4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
